backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Publish Date"
      name: "date"
      widget: "datetime"
    - label: "Tags"
      name: "tags"
      widget: "list"
      default: []
    - label: "Body"
      name: "body"
      widget: "markdown"
  - name: "currentlyReading"
    label: "Currently Reading"
    folder: "content/blog/reading"
    create: true
    slug: "{{slug}}"
    fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Author"
          name: "author"
          widget: "string"
        - label: "Genre"
          name: "genre"
          widget: "list"
          summary: "{{fields.genre}}"
          field:
            label: "Genre"
            name: "genre_item"
            widget: "string"
        - label: "Finished?"
          name: "finished"
          widget: "boolean"
          default: false
        - label: "Notes"
          name: "body"
          widget: "markdown"
          required: false
